[package]
name = "chachacha"
version = "0.1.0"
edition = "2024"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = ["nightly"]
nightly = []

[dependencies]
cfg-if = "1"

[dev-dependencies]
getrandom = "0.3"
