name: ci
on: [push, pull_request]

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        toolchain: [stable, nightly]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
    - name: Update dependencies
      run: cargo update
    - name: Enable full CPU feature set
      run: echo "RUSTFLAGS=-Ctarget-cpu=native" >> "$GITHUB_ENV"
    - name: Run tests
      if: ${{ matrix.toolchain == stable }}
      run: cargo test
      if: ${{ matrix.toolchain == nightly }}
      run: cargo test --features nightly
